title: <p align="center"> Shruti Choudhary </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/shrutichy/">LinkedIn</a> |
  <a href="https://github.com/shrutich91">GitHub</a>
  
  <br>   
  I'm working oas a Machine Learning Engineer.
  I am working in the chatbot area for over 5 years
  <br>
  </p>



theme: jekyll-theme-minimal
